export { default as upload } from './svg/upload.svg'
export { default as signUp } from './svg/signup.svg'
export { default as view } from './svg/view.svg'
export { default as pagenotfound } from './svg/pagenotfound.svg'
export { default as logo } from './svg/logo.svg'
export { default as power } from './svg/power.svg'
export { default as laughing } from './png/laughing.png'
